<?xml version="1.0" encoding="utf-8"?><Database Name="TinTucWeb2" Class="dbLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-D6N2UR3;Initial Catalog=TinTucWeb2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TinTucWeb2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ComMent" Member="ComMents">
    <Type Name="ComMent">
      <Column Name="idComMent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="idTin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tin_ComMent" Member="Tin" ThisKey="idTin" OtherKey="idTin" Type="Tin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DSMail" Member="DSMails">
    <Type Name="DSMail">
      <Column Name="idMail" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTin" Member="LoaiTins">
    <Type Name="LoaiTin">
      <Column Name="idLoaiTin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AnhHien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idTheLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LoaiTin_Tin" Member="Tins" ThisKey="idLoaiTin" OtherKey="idLoaiTin" Type="Tin" />
      <Association Name="TheLoai_LoaiTin" Member="TheLoai" ThisKey="idTheLoai" OtherKey="idTheLoai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="idMes" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mess" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tin" Member="Tins">
    <Type Name="Tin">
      <Column Name="idTin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TomTat" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="urlHinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idUser" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="idLoaiTin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTheLoai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLanXem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TinNoiBat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AnhHien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Tin_ComMent" Member="ComMents" ThisKey="idTin" OtherKey="idTin" Type="ComMent" />
      <Association Name="LoaiTin_Tin" Member="LoaiTin" ThisKey="idLoaiTin" OtherKey="idLoaiTin" Type="LoaiTin" IsForeignKey="true" />
      <Association Name="TheLoai_Tin" Member="TheLoai" ThisKey="idTheLoai" OtherKey="idTheLoai" Type="TheLoai" IsForeignKey="true" />
      <Association Name="User_Tin" Member="User" ThisKey="idUser" OtherKey="idUser" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="idTheLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AnhHien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="TheLoai_LoaiTin" Member="LoaiTins" ThisKey="idTheLoai" OtherKey="idTheLoai" Type="LoaiTin" />
      <Association Name="TheLoai_Tin" Member="Tins" ThisKey="idTheLoai" OtherKey="idTheLoai" Type="Tin" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="idUser" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDangKi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Tin" Member="Tins" ThisKey="idUser" OtherKey="idUser" Type="Tin" />
    </Type>
  </Table>
</Database>