USE [master]
GO

/****** Object:  Database [TinTucWeb]    Script Date: 09/28/2016 15:29:27 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'TinTucWeb')
DROP DATABASE [TinTucWeb]
GO

USE [master]
GO

/****** Object:  Database [TinTucWeb]    Script Date: 09/28/2016 15:29:27 ******/
CREATE DATABASE [TinTucWeb] ON  PRIMARY 
( NAME = N'TinTucWeb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TinTucWeb.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TinTucWeb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\TinTucWeb_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TinTucWeb] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TinTucWeb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TinTucWeb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TinTucWeb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TinTucWeb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TinTucWeb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TinTucWeb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TinTucWeb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TinTucWeb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TinTucWeb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TinTucWeb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TinTucWeb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TinTucWeb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TinTucWeb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TinTucWeb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TinTucWeb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TinTucWeb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TinTucWeb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TinTucWeb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TinTucWeb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TinTucWeb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TinTucWeb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TinTucWeb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TinTucWeb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TinTucWeb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TinTucWeb] SET  READ_WRITE 
GO

ALTER DATABASE [TinTucWeb] SET RECOVERY FULL 
GO

ALTER DATABASE [TinTucWeb] SET  MULTI_USER 
GO

ALTER DATABASE [TinTucWeb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TinTucWeb] SET DB_CHAINING OFF 
GO


